dist: trusty
sudo: false
group: edge
language: php
env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1

install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --verbose
